### ISSUE TITLE
override=True trait does not create a direct requirement

### ISSUE THREAD

**Issue by AbrilRBS** [jeremy-rifkin/cpp-template#1]
As per https://docs.conan.io/2/reference/conanfile/methods/requirements.html#override, the `override=True` trait in https://github.com/jeremy-rifkin/cpp-template/blob/7a728415fcf1ffb4317443f387a8900affd3af61/conanfile.py#L13 does not create a direct dependency. You might be looking for `force=True` instead :)

**Comment by jeremy-rifkin** [comment]
Thanks! Fixed now
