### ISSUE TITLE
Test requirements improvements

### ISSUE THREAD

**Issue by AbrilRBS** [jeremy-rifkin/cpp-template#2]
As per https://docs.conan.io/2/reference/conanfile/methods/build_requirements.html#test-requires, the lines in https://github.com/jeremy-rifkin/cpp-template/blob/7a728415fcf1ffb4317443f387a8900affd3af61/conanfile.py#L16 should be part of the `build_requirements()` method, and should be of the form `self.test_requires("gtest/...")`

**Comment by jeremy-rifkin** [comment]
Thanks! Fixed :)
